apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  containers:
    - name: vproapp
      image: imranvisualpath/vproappfix:latest
      ports:
        - name: vproapp-port
          containerPort: 8080      

